### ISSUE TITLE
Markdown link not linkifying

### ISSUE THREAD

**Issue by Gumnos** [SethRobertson/GitFixUm#1]
In the "Changing a single commit involving only simple commits" section, the intended link to "Post-Production Editing using Git" seems to have not been properly translated into a real link. I don't know Markdown well, but I suspect it's a pretty simple syntax tweak.  I tried to fork+fix, but couldn't find the source on Github to make it as easy for you as a pull req.

**Comment by SethRobertson** [comment]
Thanks.  Fixed.
