### ISSUE TITLE
Removing multiple commits.

### ISSUE THREAD

**Issue by lgedeon** [SethRobertson/GitFixUm#19]
Thank you! I absolutely love this. It has helped me many, many times, but for the first time I reached the end and still wasn't sure what to do.

I got to the point where I needed to revert a merge but that particular merge was from a branch that had recently branched of master and so when it was merged in there was no merge commit. It just put all the commits in as if they had been made individually to master.

I found out that I could revert each commit individually, but I am wondering if there is a better way. Either way, it might be helpful to add a note that there may not be a merge commit available to be reverted in some cases.

**Comment by SethRobertson** [comment]
What you experienced is a "fast-forward" merge.  You can eliminate these by using the `--no-ff` option to git merge (or setting merge.ff to false in your git-config).

However, without a merge commit, the situation you were in was exactly like you just made simple commits, and the part of the fix-um that does that explains how to revert multiple commits: http://sethrobertson.github.io/GitFixUm/fixup.html#pushed_new_simple

I'll try to make a change which will help others in the future.  Only 561 days later!
