### ISSUE TITLE
Funny link ("Yes I want to remove an entire commit")

### ISSUE THREAD

**Issue by PhilippePerret** [SethRobertson/GitFixUm#24]
![bug](https://user-images.githubusercontent.com/610524/101152146-f1e47000-3622-11eb-872e-8d87bfb0729a.gif)

**Comment by SethRobertson** [comment]
Hah, breadcrumb tracking gone wrong.

This feature is showing you how to got to the page you were on, to help you figure out what state you were in.  In your case you are clicking on a link to the current page so it adds the current page to the list of links.

Technically correct and matching what the back button would show, but perhaps not entirely expected.  If you submit a patch, I'll apply it.
