### ISSUE TITLE
Add offline support

### ISSUE THREAD

**Issue by Skalman** [SethRobertson/GitFixUm#4]
It would be great to support offline mode. This document would be useful to have, even when not online.

I suggest adding an application cache.

**Comment by goneng** [comment]
I thought so as well, and created an "offline" version of this site, with the help of Seth.
Currently available for iOS devices - see 'git Help' for iPhone or iPad:
https://itunes.apple.com/us/app/git-help/id665737894?mt=8&uo=4

Let me know what you think.

**Comment by Skalman** [comment]
I don't use Apple products and I don't see the reason not to have this available on all platforms.

For now, an offline version is available on http://skalman.github.io/GitFixUm/fixup.html

**Comment by Skalman** [comment]
@goneng The difference is that your browser (IE 10+ and every other modern browser) will save a version of the page for offline use. You won't notice any difference, but the site will load instantly and it'll work also when offline.
