### ISSUE TITLE
I have (unpushed) commits on a branch and I want to split one commit into two smaller ones

### ISSUE THREAD

**Issue by eordano** [SethRobertson/GitFixUm#6]
This is a change that I sometimes want to introduce and I always end up tagging the commit to be rewritten, `reset --hard` to the previous one, `checkout` file by file and `add -p` to make sure I'm adding just what I need, and a `rebase` of the older branch. I find this process to be painful, very painful (and I couldn't think of a better way); and I was wondering if you had any ideas to make it easier to digest.

**Comment by goneng** [comment]
I think there is a simpler approach:
1. git reset ("soft") to the prior commit-ID
   (Now, all changes are showing as uncommitted changes)
2. git add (to a group of files)
3. git commit
4. Go back to step '2.' until done with all the files.

Cheers

Gonen Goshen
052-6116506

‫ב-1 באפר 2014, בשעה 17:18, ‏Esteban Ordano notifications@github.com כתב/ה:‬

This is a change that I sometimes want to introduce and I always end up tagging the commit to be rewritten, reset --hard to the previous one, checkout file by file and add -p to make sure I'm adding just what I need, and a rebase of the older branch. I find this process to be painful, very painful (and I couldn't think of a better way); and I was wondering if you had any ideas to make it easier to digest.

**Comment by eordano** [comment]
I'll give it a try! Thanks

**Comment by goneng** [comment]
If this is what you were looking for,
I would add steps '0.', '5.' and '6.' to the process:
1. save your current state in temp-branch 'state-before-splitting-commits':
   git branch state-before-splitting-commits
2. git reset ("soft") to the prior commit-ID
   (Now, all changes are showing as uncommitted changes)
3. git add (to a group of files)
4. git commit
5. Go back to step '2.' until done with all the files
6. Confirm all is same as before - compare to the original state:
   git diff state-before-splitting-commits..HEAD
   (if all is well - there should be NO differences)
7. drop the temp-branch:
   git branch -D state-before-splitting-commits
