### ISSUE TITLE
web app

### ISSUE THREAD

**Issue by mjhea0** [SethRobertson/GitFixUm#8]
i love this. it would look really pretty as a nice interactive site with jquery or angular to eliminate clutter. what to team up and make it look nice (err, nicer)?

**Comment by SethRobertson** [comment]
As you have noted, the current version is not very sophisticated which pretty much represents the limit of my graphical design capabilities.  That being said, I appreciate a clean design and a bit of prettyness, as long as it does not go too far (function over form).

So, I am happy to accept pull requests adding beauty or discuss the appropriateness of various changes.  However, my requirements for accepting changes is that the page remains responsive even on low-power systems, that the page remains functional even on very primitive systems (like text-only browsers or cell phone browsers), and that changes remain easy to manually implement.
