### ISSUE TITLE
I did a terrible terrible thing.

### ISSUE THREAD

**Issue by ghost** [SethRobertson/GitFixUm#9]
So, i was on master, made some changes to a file, before i could commit, someone else from the team merged a branch to the master. I know i should never commit directly to master, lesson learnt the hard way :( but then i committed my changes onto the master (i had the copy of master before someone else did the branch merge) Now my commit seems to break the master. I want to revert back to the place where merge was made by someone else. i have my changes which i can add later. i cant find a way to revert back to that commit.
Please help me out whats the best way to fix it.

**Comment by goneng** [comment]
As with everything related to git, there are at least two ways to handle this...
1. The Bad Way - Changing History:
   you force-push 'origin/master' to point to the commit that is OK
   (the one before yours).
   this is somewhat acceptable only for very small projects,
   where you can go talk to everyone and MAKE SURE they pull the correct version of the branch,
   which is any version prior to your bad-merge!
   (it is enough that one of the guys have pulled your version of the master,
    and you are back where you have started...)
2. The Better Way - Git-Revert your commit
   Read about git-revert here: http://git-scm.com/blog/2010/03/02/undoing-merges.html
   you will need to specify the side of the merge you wish to keep ('-m 1' or '-m 2') -
   $ git revert -m 1 [sha_of_merge-commit]
   I always get those wrong, and do the revert again
   (no harm - just drop the revert-commit and run the command again)

Good luck!

**Comment by ghost** [comment]
thanks :+1: that worked
